//
// Created by coldc on 5/1/2022.
//

#ifndef BOOKRESERVATIONSYSTEM_V0_0_1_DATABASECONNECTION_H
#define BOOKRESERVATIONSYSTEM_V0_0_1_DATABASECONNECTION_H


class DatabaseConnection {

};


#endif //BOOKRESERVATIONSYSTEM_V0_0_1_DATABASECONNECTION_H
